### PR TITLE
Add upcoming meetups to the list

### PR DESCRIPTION
**Pull request by martgnz**
If we have upcoming meetups listed they will be shown under their own section.

Extra ball: show the correct meetup dates and link to the venue address.

### CODE REVIEW

**Comment by tsdgeos** [comment]
How hard would it me to make it so that if there are not upcoming meetups we show something that says

Upcoming Meetups
None planned for the moment. Do you have something interesting to talk? Contact us! (with the link to the mailing list)

Do you think it makes sense?

**Comment by martgnz** [comment]
That was my idea at the beginning but then I switched to hide the whole section because somehow it felt cleaner...

But yeah, you're right, this could encourage people to submit.

**Comment by martgnz** [comment]
You can check again @tsdgeos. Now it shows the placeholder when there's nothing planned.

**Comment by tsdgeos** [comment]
Code looks generally good from my "i don't really know much of this language" point of view.

Unless Aleix disagrees i'd say commit it and if something breaks we'll just fix it when it does :smile:

**Comment by aleixpol** [comment]
Gràcies! :)

**Pull request merged**
